// client/src/ui/components/rs/RsInterface.svelte
<script lang="ts">
    import { onDestroy } from "svelte";

    import {
        InterfaceManager,
        Interpreter,
        nudgeScrollY,
        setCs1InterfaceEntry,
        setCs1SimState,
        setCs1VarbitDefinitionLookup,
        setInterfaceMousePosition,
    } from "../../../lib/interface-renderer/interface-manager";
    import type { ComponentType, InterfaceEntry } from "../../../lib/interface-renderer/component-types";
    import type { Cs1SimState } from "../../../lib/interface-renderer/cs1-interpreter";
    import { applyCs2RuntimeFromSim } from "../../../lib/interface-renderer/cs2/runtime-context";
    import type { CacheIndex } from "../../../rs/cache/CacheIndex";
    import type { VarbitDefinitionLookup } from "../../../rs/config/vartype/bit/VarBitTypeLoader";
    import type { Sprite } from "../../../rs/sprite/InterfaceCanvasSprite";
    import type { RsInterfaceMode } from "../../../interface/interface-editor-workbench-model";
    import { elementSize } from "../../lib/actions";

    const FIXED_CANVAS_WIDTH = 765;
    const FIXED_CANVAS_HEIGHT = 503;
    const FIXED_VIEWPORT_WIDTH = 512;
    const FIXED_VIEWPORT_HEIGHT = 334;
    const FIXED_VIEWPORT_OFFSET_X = 4;
    const FIXED_VIEWPORT_OFFSET_Y = 4;

    let {
        interfaceId,
        mode,
        isInterfaceLoaded = true,
        interfaceData,
        revision = "latest",
        cacheHeaders = {},
        spritesById = new Map<number, Sprite>(),
        clientScriptIndex = null,
        class: className = "",
        viewportColor = "rgb(76,68,32)",
        showOverlays = true,
        showViewportBorder = false,
        showPixelGrid = false,
        selectedComponentId = null,
        selectedComponent = null,
        interactiveMode = false,
        cs1SimState = null,
        cs1VarbitDefinitionLookup = null,
        cs2RedrawNonce = 0,
    }: {
        interfaceId: number | null;
        mode: RsInterfaceMode;
        isInterfaceLoaded?: boolean;
        interfaceData?: InterfaceEntry | null;
        revision?: string | number;
        cacheHeaders?: HeadersInit;
        spritesById?: ReadonlyMap<number, Sprite>;
        clientScriptIndex?: CacheIndex | null;
        class?: string;
        viewportColor?: string;
        showOverlays?: boolean;
        showViewportBorder?: boolean;
        showPixelGrid?: boolean;
        selectedComponentId?: number | null;
        selectedComponent?: ComponentType | null;
        interactiveMode?: boolean;
        cs1SimState?: Cs1SimState | null;
        cs1VarbitDefinitionLookup?: VarbitDefinitionLookup | null;
        cs2RedrawNonce?: number;
    } = $props();

    let container = $state<HTMLDivElement>();
    let canvas = $state<HTMLCanvasElement>();
    let containerWidth = $state(0);
    let containerHeight = $state(0);
    let manager: InterfaceManager | null = null;
    let hoverPick: ComponentType | null = null;
    let renderRaf = 0;

    const viewportWidth = $derived(mode === "fixed" ? FIXED_VIEWPORT_WIDTH : containerWidth);
    const viewportHeight = $derived(mode === "fixed" ? FIXED_VIEWPORT_HEIGHT : containerHeight);
    const viewportOffsetX = $derived(mode === "fixed" ? FIXED_VIEWPORT_OFFSET_X : 0);
    const viewportOffsetY = $derived(mode === "fixed" ? FIXED_VIEWPORT_OFFSET_Y : 0);
    const canvasWidth = $derived(mode === "fixed" ? FIXED_CANVAS_WIDTH : Math.max(1, containerWidth));
    const canvasHeight = $derived(mode === "fixed" ? FIXED_CANVAS_HEIGHT : Math.max(1, containerHeight));

    function componentRuntimeId(component: ComponentType): number {
        return typeof component.packedId === "number" ? component.packedId : component.id;
    }

    function collectAllComponents(data: InterfaceEntry): ComponentType[] {
        const result: ComponentType[] = [];
        const seen = new Set<ComponentType>();
        const visit = (component: ComponentType): void => {
            if (seen.has(component)) return;
            seen.add(component);
            result.push(component);
            for (const child of component.children ?? []) {
                if (child) visit(child);
            }
        };
        for (const component of Object.values(data.components)) visit(component);
        return result;
    }

    function localPosition(event: MouseEvent): { x: number; y: number } {
        if (!canvas) return { x: 0, y: 0 };
        const rect = canvas.getBoundingClientRect();
        return {
            x: (event.clientX - rect.left) * (canvas.width / rect.width || 1),
            y: (event.clientY - rect.top) * (canvas.height / rect.height || 1),
        };
    }

    function pickComponentAt(data: InterfaceEntry, x: number, y: number): ComponentType | null {
        const currentManager = manager;
        if (!currentManager) return null;
        let best: ComponentType | null = null;
        let bestArea = Infinity;
        for (const component of collectAllComponents(data)) {
            const bounds = currentManager.getComponentDrawBoundsFor(component);
            if (!bounds) continue;
            if (x < bounds.x || x >= bounds.x + bounds.width || y < bounds.y || y >= bounds.y + bounds.height) continue;
            const area = bounds.width * bounds.height;
            if (area < bestArea) {
                bestArea = area;
                best = component;
            }
        }
        return best;
    }

    function pickScrollableAt(
        data: InterfaceEntry,
        x: number,
        y: number,
    ): { runtimeId: number; scrollHeight: number; tempHeight: number } | null {
        const currentManager = manager;
        if (!currentManager) return null;
        let best: { runtimeId: number; scrollHeight: number; tempHeight: number } | null = null;
        let bestArea = Infinity;
        for (const component of collectAllComponents(data)) {
            if (component.type !== 0 && component.type !== 11) continue;
            if (component.scrollHeight <= component.tempHeight) continue;
            const bounds = currentManager.getComponentDrawBoundsFor(component);
            if (!bounds) continue;
            if (x < bounds.x || x >= bounds.x + bounds.width || y < bounds.y || y >= bounds.y + bounds.height) continue;
            const area = bounds.width * bounds.height;
            if (area < bestArea) {
                bestArea = area;
                best = {
                    runtimeId: componentRuntimeId(component),
                    scrollHeight: component.scrollHeight,
                    tempHeight: component.tempHeight,
                };
            }
        }
        return best;
    }

    function draw(
        context: CanvasRenderingContext2D,
        currentManager: InterfaceManager,
        data: InterfaceEntry,
        id: number,
    ): void {
        setCs1SimState(cs1SimState ?? null);
        setCs1InterfaceEntry(data);
        setCs1VarbitDefinitionLookup(cs1VarbitDefinitionLookup ?? null);
        applyCs2RuntimeFromSim(
            cs1SimState,
            revision,
            cacheHeaders,
            cs1VarbitDefinitionLookup ?? null,
            data,
            canvasWidth,
            canvasHeight,
            clientScriptIndex,
        );

        context.setTransform(1, 0, 0, 1, 0, 0);
        context.imageSmoothingEnabled = false;
        context.clearRect(0, 0, canvasWidth, canvasHeight);
        currentManager.drawWidgets(
            data,
            id,
            viewportOffsetX,
            viewportOffsetY,
            viewportOffsetX + viewportWidth,
            viewportOffsetY + viewportHeight,
            viewportOffsetX,
            viewportOffsetY,
            -1,
        );

        if (selectedComponent != null || selectedComponentId != null) {
            const bounds =
                selectedComponent != null
                    ? currentManager.getComponentDrawBoundsFor(selectedComponent)
                    : currentManager.getComponentDrawBounds(selectedComponentId!);
            if (bounds) {
                context.save();
                context.globalAlpha = 1;
                context.strokeStyle = "#00e5ff";
                context.lineWidth = 1;
                context.setLineDash([3, 2]);
                context.strokeRect(bounds.x + 0.5, bounds.y + 0.5, bounds.width, bounds.height);
                context.fillStyle = "rgba(0,229,255,0.15)";
                context.fillRect(bounds.x, bounds.y, bounds.width, bounds.height);
                context.restore();
            }
        }
    }

    $effect(() => {
        const target = canvas;
        const data = interfaceData;
        const id = interfaceId;
        const width = canvasWidth;
        const height = canvasHeight;
        const redraw = cs2RedrawNonce;
        const selectedId = selectedComponentId;
        const selected = selectedComponent;
        const simState = cs1SimState;
        const lookup = cs1VarbitDefinitionLookup;
        const rev = revision;
        const headers = cacheHeaders;
        const sprites = spritesById;
        const scriptIndex = clientScriptIndex;
        viewportOffsetX;
        viewportOffsetY;
        viewportWidth;
        viewportHeight;

        if (!target || !data || id == null || width <= 0 || height <= 0) return;
        void redraw;
        void selectedId;
        void selected;
        void simState;
        void lookup;
        void rev;
        void headers;
        void scriptIndex;

        target.width = width;
        target.height = height;
        const context = target.getContext("2d");
        if (!context) return;

        const nextManager = new InterfaceManager(context, sprites);
        manager = nextManager;

        const frame = (): void => {
            draw(context, nextManager, data, id);
            renderRaf = requestAnimationFrame(frame);
        };
        draw(context, nextManager, data, id);
        renderRaf = requestAnimationFrame(frame);

        return () => {
            cancelAnimationFrame(renderRaf);
            if (manager === nextManager) manager = null;
            setCs1SimState(null);
            setCs1InterfaceEntry(null);
            setCs1VarbitDefinitionLookup(null);
        };
    });

    $effect(() => {
        if (interactiveMode) return;
        Interpreter.mousedOverWidgetIf1 = null;
        Interpreter.clickedWidget = null;
        hoverPick = null;
    });

    function onMouseMove(event: MouseEvent): void {
        const position = localPosition(event);
        setInterfaceMousePosition(position.x, position.y);
        if (!interactiveMode || !interfaceData) return;
        const next = pickComponentAt(interfaceData, position.x, position.y);
        if (next !== hoverPick) {
            hoverPick = next;
            Interpreter.mousedOverWidgetIf1 = next;
        }
    }

    function onMouseLeave(): void {
        setInterfaceMousePosition(0, 0);
        if (hoverPick !== null) {
            hoverPick = null;
            Interpreter.mousedOverWidgetIf1 = null;
        }
    }

    function onWheel(event: WheelEvent): void {
        if (!interactiveMode || !interfaceData) return;
        event.preventDefault();
        const position = localPosition(event);
        const picked = pickScrollableAt(interfaceData, position.x, position.y);
        if (!picked) return;
        nudgeScrollY(picked.runtimeId, event.deltaY, picked.scrollHeight, picked.tempHeight);
    }

    function onMouseDown(event: MouseEvent): void {
        if (!interactiveMode || !interfaceData) return;
        const position = localPosition(event);
        Interpreter.clickedWidget = pickComponentAt(interfaceData, position.x, position.y);
    }

    function clearClicked(): void {
        Interpreter.clickedWidget = null;
    }

    $effect(() => {
        if (!interactiveMode) return;
        window.addEventListener("mouseup", clearClicked);
        return () => window.removeEventListener("mouseup", clearClicked);
    });

    onDestroy(() => {
        cancelAnimationFrame(renderRaf);
        manager = null;
        Interpreter.mousedOverWidgetIf1 = null;
        Interpreter.clickedWidget = null;
        setCs1SimState(null);
        setCs1InterfaceEntry(null);
        setCs1VarbitDefinitionLookup(null);
    });
</script>

<div
    bind:this={container}
    use:elementSize={(size) => {
        containerWidth = Math.floor(size.width);
        containerHeight = Math.floor(size.height);
    }}
    class={`relative overflow-hidden bg-black ${className}`}
    class:shrink-0={mode === "fixed"}
    style:min-width={mode === "fixed" ? `${FIXED_CANVAS_WIDTH}px` : undefined}
    style:min-height={mode === "fixed" ? `${FIXED_CANVAS_HEIGHT}px` : undefined}
    style:width={mode === "fixed" ? `${FIXED_CANVAS_WIDTH}px` : undefined}
    style:height={mode === "fixed" ? `${FIXED_CANVAS_HEIGHT}px` : undefined}
>
    <div
        class="absolute z-0"
        style:left="{viewportOffsetX}px"
        style:top="{viewportOffsetY}px"
        style:width="{viewportWidth}px"
        style:height="{viewportHeight}px"
        style:background-color={viewportColor}
        style:background-image={showPixelGrid
            ? "linear-gradient(to right, rgba(255,255,255,0.16) 1px, transparent 1px), linear-gradient(to bottom, rgba(255,255,255,0.16) 1px, transparent 1px)"
            : "none"}
        style:background-size={showPixelGrid ? "4px 4px" : undefined}
        style:border={showViewportBorder ? "1px solid rgba(255,255,255,0.45)" : "none"}
    ></div>

    <canvas
        bind:this={canvas}
        class="absolute left-0 top-0 z-10"
        class:pointer-events-none={!interactiveMode}
        style="image-rendering: pixelated; width: {canvasWidth}px; height: {canvasHeight}px; min-width: {canvasWidth}px; min-height: {canvasHeight}px; max-width: none; max-height: none; flex-shrink: 0;"
        onmousemove={onMouseMove}
        onmouseleave={onMouseLeave}
        onwheel={onWheel}
        onmousedown={onMouseDown}
        onmouseup={clearClicked}
    ></canvas>

    {#if showOverlays && mode === "fixed"}
        <img
            src="/ui/fixed_ui.png"
            alt="Fixed UI overlay"
            width={FIXED_CANVAS_WIDTH}
            height={FIXED_CANVAS_HEIGHT}
            class="pointer-events-none absolute left-0 top-0 z-20"
        />
    {:else if showOverlays}
        <img src="/ui/resized_chat.png" alt="Chat overlay" class="pointer-events-none absolute bottom-0 left-0 z-20 object-contain" width="519" height="142" />
        <img src="/ui/resized_map.png" alt="Map overlay" class="pointer-events-none absolute right-0 top-0 z-20 object-contain" width="211" height="194" />
        <img src="/ui/resized_tab.png" alt="Tab overlay" class="pointer-events-none absolute bottom-0 right-0 z-20 object-contain" width="249" height="336" />
    {/if}

    {#if !isInterfaceLoaded}
        <div class="pointer-events-none absolute inset-0 z-30 flex items-center justify-center">
            <div class="flex items-center gap-2 rounded bg-black/40 px-2 py-1 text-xs text-white">
                <div class="h-5 w-5 animate-spin rounded-full border-2 border-white/30 border-t-white"></div>
                <span>Loading interface...</span>
            </div>
        </div>
    {/if}
</div>

// client/src/app/interface/RsInterface.tsx
﻿"use client";

import Image from "next/image";
import * as React from "react";



import { InterfaceManager, Interpreter, nudgeScrollY, setInterfaceMousePosition } from "../../lib/interfaces/InterfaceManager";
import { ComponentType } from "../../rs/config/components/ComponentType";
import { InterfaceType } from "../../rs/config/components/InterfaceType";


const FIXED_CANVAS_WIDTH = 765;
const FIXED_CANVAS_HEIGHT = 503;
const FIXED_VIEWPORT_WIDTH = 512;
const FIXED_VIEWPORT_HEIGHT = 334;
const FIXED_VIEWPORT_OFFSET_X = 4;
const FIXED_VIEWPORT_OFFSET_Y = 4;

export type RsInterfaceMode = "fixed" | "resizable";

export type RsInterfaceProps = {
    interfaceId: number | null;
    mode: RsInterfaceMode;
    isInterfaceLoaded?: boolean;
    interfaceData?: InterfaceType | null;
    revision?: string | number;
    cacheHeaders?: HeadersInit;
    className?: string;
    viewportColor?: string;
    showOverlays?: boolean;
    showViewportBorder?: boolean;
    showPixelGrid?: boolean;
    selectedComponentId?: number | null;
    selectedComponent?: ComponentType | null;
    interactiveMode?: boolean;
};

function useContainerSize(ref: React.RefObject<HTMLDivElement | null>): {
    width: number;
    height: number;
} {
    const [size, setSize] = React.useState({ width: 0, height: 0 });

    React.useEffect(() => {
        const el = ref.current;
        if (!el) return;
        const observer = new ResizeObserver((entries) => {
            const entry = entries[0];
            if (!entry) return;
            setSize({
                width: Math.floor(entry.contentRect.width),
                height: Math.floor(entry.contentRect.height),
            });
        });
        observer.observe(el);
        setSize({ width: Math.floor(el.clientWidth), height: Math.floor(el.clientHeight) });
        return () => observer.disconnect();
    }, [ref]);

    return size;
}

function componentRuntimeId(comp: ComponentType): number {
    return comp.internalId;
}


function canvasLocalFromClient(
    canvas: HTMLCanvasElement,
    clientX: number,
    clientY: number,
): { x: number; y: number } {
    const rect = canvas.getBoundingClientRect();
    const scaleX = canvas.width / rect.width || 1;
    const scaleY = canvas.height / rect.height || 1;
    return {
        x: (clientX - rect.left) * scaleX,
        y: (clientY - rect.top) * scaleY,
    };
}



function collectAllComponents(entry: InterfaceType): ComponentType[] {
    const out: ComponentType[] = [];
    const visit = (c: ComponentType) => {
        out.push(c);
    };
    for (const c of Object.values(entry.components)) {
        visit(c);
    }
    return out;
}


function useInterfaceRenderer(
    canvasRef: React.RefObject<HTMLCanvasElement | null>,
    interfaceId: number | null,
    interfaceData: InterfaceType | null | undefined,
    revision: string | number,
    viewportOffsetX: number,
    viewportOffsetY: number,
    viewportWidth: number,
    viewportHeight: number,
    selectedComponentId: number | null,
    selectedComponent: ComponentType | null,
    redrawTick: number,
    managerOutRef: React.MutableRefObject<InterfaceManager | null>,
) {
    const renderRedrawRef = React.useRef<(() => void) | null>(null);
    const interfaceDataRef = React.useRef(interfaceData);
    const interfaceIdRef = React.useRef(interfaceId);
    React.useLayoutEffect(() => {
        interfaceDataRef.current = interfaceData;
        interfaceIdRef.current = interfaceId;
    });

    React.useEffect(() => {
        const canvas = canvasRef.current;

        if (!canvas || !interfaceData || interfaceId == null) return;

        const ctx = canvas.getContext("2d");
        if (!ctx) return;

        const manager = new InterfaceManager(ctx, revision);
        managerOutRef.current = manager;
        render(ctx, manager);

        function render(ctx: CanvasRenderingContext2D, mgr: InterfaceManager) {
            //setCs1SimState(cs1SimStateRef.current ?? null);
            const data = interfaceDataRef.current;
            const iid = interfaceIdRef.current;
            if (!data || iid == null) {
                return;
            }

            ctx.setTransform(1, 0, 0, 1, 0, 0);
            ctx.imageSmoothingEnabled = false;
            ctx.clearRect(0, 0, canvas!.width, canvas!.height);

            mgr.drawWidgets(
                data,
                iid,
                viewportOffsetX,
                viewportOffsetY,
                viewportOffsetX + viewportWidth,
                viewportOffsetY + viewportHeight,
                viewportOffsetX,
                viewportOffsetY,
                -1,
            );

            if (selectedComponent != null || selectedComponentId != null) {
                const bounds =
                    selectedComponent != null
                        ? mgr.getComponentDrawBoundsFor(selectedComponent)
                        : mgr.getComponentDrawBounds(selectedComponentId!);
                if (bounds) {
                    ctx.save();
                    ctx.globalAlpha = 1;
                    ctx.strokeStyle = "#00e5ff";
                    ctx.lineWidth = 1;
                    ctx.setLineDash([3, 2]);
                    ctx.strokeRect(bounds.x + 0.5, bounds.y + 0.5, bounds.width, bounds.height);
                    ctx.fillStyle = "rgba(0,229,255,0.15)";
                    ctx.fillRect(bounds.x, bounds.y, bounds.width, bounds.height);
                    ctx.restore();
                }
            }
        }

        let rafId: number | null = null;
        const frame = () => {
            render(ctx, manager);
            rafId = window.requestAnimationFrame(frame);
        };

        render(ctx, manager);
        rafId = window.requestAnimationFrame(frame);

        renderRedrawRef.current = () => {
            render(ctx, manager);
        };

        return () => {
            if (rafId != null) {
                window.cancelAnimationFrame(rafId);
            }
            managerOutRef.current = null;
            renderRedrawRef.current = null;
        };
    }, [
        canvasRef,
        interfaceId,
        interfaceData,
        revision,
        viewportOffsetX,
        viewportOffsetY,
        viewportWidth,
        viewportHeight,
        selectedComponentId,
        selectedComponent,
        managerOutRef
    ]);

    React.useEffect(() => {
        if (redrawTick === 0) return;
        renderRedrawRef.current?.();
    }, [redrawTick]);
}

export function RsInterface({
    interfaceId,
    mode,
    interfaceData,
    revision = "latest",
    className,
    viewportColor = "rgb(76,68,32)",
    showOverlays = true,
    showViewportBorder = false,
    showPixelGrid = false,
    selectedComponentId = null,
    selectedComponent = null,
    interactiveMode = false
}: RsInterfaceProps) {
    const containerRef = React.useRef<HTMLDivElement>(null);
    const canvasRef = React.useRef<HTMLCanvasElement>(null);
    const managerOutRef = React.useRef<InterfaceManager | null>(null);

    const [redrawTick, setRedrawTick] = React.useState(0);
    const bumpRedraw = React.useCallback(() => {
        setRedrawTick((t) => t + 1);
    }, []);
    const hoverPickRef = React.useRef<ComponentType | null>(null);
    const [displayScale, setDisplayScale] = React.useState<{ x: number; y: number }>({
        x: 1,
        y: 1,
    });
    const { width: containerWidth, height: containerHeight } = useContainerSize(containerRef);

    const viewportWidth = mode === "fixed" ? FIXED_VIEWPORT_WIDTH : containerWidth;
    const viewportHeight = mode === "fixed" ? FIXED_VIEWPORT_HEIGHT : containerHeight;
    const viewportOffsetX = mode === "fixed" ? FIXED_VIEWPORT_OFFSET_X : 0;
    const viewportOffsetY = mode === "fixed" ? FIXED_VIEWPORT_OFFSET_Y : 0;

    const canvasW = mode === "fixed" ? FIXED_CANVAS_WIDTH : containerWidth;
    const canvasH = mode === "fixed" ? FIXED_CANVAS_HEIGHT : containerHeight;

    const fixedStyle: React.CSSProperties =
        mode === "fixed" ? { width: FIXED_CANVAS_WIDTH, height: FIXED_CANVAS_HEIGHT } : {};

    useInterfaceRenderer(
        canvasRef,
        interfaceId,
        interfaceData,
        revision,
        viewportOffsetX,
        viewportOffsetY,
        viewportWidth,
        viewportHeight,
        selectedComponentId,
        selectedComponent,
        redrawTick,
        managerOutRef
    );

    React.useEffect(() => {
        if (interactiveMode) return;
        Interpreter.mousedOverWidgetIf1 = null;
        Interpreter.clickedWidget = null;
        hoverPickRef.current = null;
    }, [interactiveMode]);

    React.useEffect(() => {
        if (!interactiveMode || !interfaceData || interfaceId == null) return;
        const canvas = canvasRef.current;
        if (!canvas) return;

        const onMove = (e: MouseEvent) => {
            const { x, y } = canvasLocalFromClient(canvas, e.clientX, e.clientY);
            setInterfaceMousePosition(x, y);
            const mgr = managerOutRef.current;
            if (!mgr) return;
            const next = pickComponentAt(interfaceData, x, y, mgr);
            if (next !== hoverPickRef.current) {
                hoverPickRef.current = next;
                Interpreter.mousedOverWidgetIf1 = next;
                bumpRedraw();
            }
        };

        const onLeave = () => {
            setInterfaceMousePosition(0, 0);
            if (hoverPickRef.current !== null) {
                hoverPickRef.current = null;
                Interpreter.mousedOverWidgetIf1 = null;
                bumpRedraw();
            }
        };

        const onWheel = (e: WheelEvent) => {
            e.preventDefault();
            const mgr = managerOutRef.current;
            if (!mgr) return;
            const { x, y } = canvasLocalFromClient(canvas, e.clientX, e.clientY);
            const picked = pickScrollableAt(interfaceData, x, y, mgr);
            if (!picked) return;
            nudgeScrollY(picked.runtimeId, e.deltaY, picked.scrollHeight, picked.tempHeight);
            bumpRedraw();
        };

        const onDown = (e: MouseEvent) => {
            const mgr = managerOutRef.current;
            if (!mgr) return;
            const { x, y } = canvasLocalFromClient(canvas, e.clientX, e.clientY);
            Interpreter.clickedWidget = pickComponentAt(interfaceData, x, y, mgr);
            bumpRedraw();
        };

        const onUp = () => {
            if (Interpreter.clickedWidget !== null) {
                Interpreter.clickedWidget = null;
                bumpRedraw();
            }
        };

        canvas.addEventListener("mousemove", onMove);
        canvas.addEventListener("mouseleave", onLeave);
        canvas.addEventListener("wheel", onWheel, { passive: false });
        canvas.addEventListener("mousedown", onDown);
        canvas.addEventListener("mouseup", onUp);
        window.addEventListener("mouseup", onUp);
        return () => {
            canvas.removeEventListener("mousemove", onMove);
            canvas.removeEventListener("mouseleave", onLeave);
            canvas.removeEventListener("wheel", onWheel);
            canvas.removeEventListener("mousedown", onDown);
            canvas.removeEventListener("mouseup", onUp);
            window.removeEventListener("mouseup", onUp);
        };
    }, [interactiveMode, interfaceData, interfaceId, bumpRedraw]);

    React.useEffect(() => {
        const canvas = canvasRef.current;
        if (!canvas || mode !== "fixed") return;
        const rect = canvas.getBoundingClientRect();
        const scaleX = rect.width / canvas.width;
        const scaleY = rect.height / canvas.height;
        setDisplayScale({ x: scaleX, y: scaleY });
    }, [mode, canvasW, canvasH]);

    const handleCanvasMouseMove = React.useCallback((e: React.MouseEvent<HTMLCanvasElement>) => {
        const c = e.currentTarget;
        const { x, y } = canvasLocalFromClient(c, e.clientX, e.clientY);
        setInterfaceMousePosition(x, y);
    }, []);

    return (
        <div
            ref={containerRef}
            className={`relative overflow-hidden bg-black ${className ?? ""}`}
            style={{
                ...fixedStyle,
                flexShrink: 0,
                minWidth: mode === "fixed" ? FIXED_CANVAS_WIDTH : undefined,
                minHeight: mode === "fixed" ? FIXED_CANVAS_HEIGHT : undefined,
            }}
            data-display-scale={`${displayScale.x.toFixed(3)}x${displayScale.y.toFixed(3)}`}
        >
            <div
                className="absolute z-0"
                style={{
                    left: viewportOffsetX,
                    top: viewportOffsetY,
                    width: viewportWidth,
                    height: viewportHeight,
                    backgroundColor: viewportColor,
                    backgroundImage: showPixelGrid
                        ? "linear-gradient(to right, rgba(255,255,255,0.16) 1px, transparent 1px), linear-gradient(to bottom, rgba(255,255,255,0.16) 1px, transparent 1px)"
                        : "none",
                    backgroundSize: showPixelGrid ? "4px 4px" : undefined,
                    border: showViewportBorder ? "1px solid rgba(255,255,255,0.45)" : "none",
                }}
            />

            <canvas
                ref={canvasRef}
                width={canvasW}
                height={canvasH}
                onMouseMove={interactiveMode ? undefined : handleCanvasMouseMove}
                className={`absolute left-0 top-0 z-10 ${
                    interactiveMode ? "" : "pointer-events-none"
                }`}
                style={{
                    imageRendering: "pixelated",
                    width: `${canvasW}px`,
                    height: `${canvasH}px`,
                    minWidth: `${canvasW}px`,
                    minHeight: `${canvasH}px`,
                    maxWidth: "none",
                    maxHeight: "none",
                    flexShrink: 0,
                }}
            />

            {showOverlays && mode === "fixed" ? (
                <Image
                    src="/ui/fixed_ui.png"
                    alt="Fixed UI overlay"
                    width={FIXED_CANVAS_WIDTH}
                    height={FIXED_CANVAS_HEIGHT}
                    className="pointer-events-none absolute left-0 top-0 z-20"
                    priority
                    unoptimized
                />
            ) : showOverlays ? (
                <>
                    <Image
                        src="/ui/resized_chat.png"
                        alt="Chat overlay"
                        className="pointer-events-none absolute bottom-0 left-0 z-20 object-contain"
                        width={519}
                        height={142}
                        unoptimized
                    />
                    <Image
                        src="/ui/resized_map.png"
                        alt="Map overlay"
                        className="pointer-events-none absolute right-0 top-0 z-20 object-contain"
                        width={211}
                        height={194}
                        unoptimized
                    />
                    <Image
                        src="/ui/resized_tab.png"
                        alt="Tab overlay"
                        className="pointer-events-none absolute bottom-0 right-0 z-20 object-contain"
                        width={249}
                        height={336}
                        unoptimized
                    />
                </>
            ) : null}
        </div>
    );
}
